### ISSUE TITLE
你好！为什么我在训练的时候acc一直没有变化？损失也没有变化

### ISSUE THREAD

**Issue by Jockey721** [integeruser/CASIA-HWDB1.1-cnn#1]
15个epoch之后，好像没有学到任何东西？
![image](https://user-images.githubusercontent.com/27748275/70845435-ac66ea00-1e89-11ea-80f1-a61cf9cfb5e7.png)

**Comment by lyu-dimo** [comment]
你好，根据我之前遇到的问题，可能造成的原因有以下几点：
1.卷积层数太少，深度不够（我是参考的谷歌的深度学习框架架构进行一些修改）；
2.训练的汉字字数太多，我是先从200个汉字进行训练的，如果训练全部汉字需要更改学习框架的代码（好像是在每一卷积层后增加了一句代码，不好意思，时间久远具体怎么修改已经忘记了，请google搜索）；
3.训练的次数太少，汉字识别相比于数字识别需要更多次的训练次数；


ps：我是从18年9月份开始接触学习的深度学习框架，从19年开始专注学习Java，以上原因有可能不准确，希望能给你一些提示，如果不能解决请前去google。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"812618101"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月14日(星期六) 下午3:52
收件人:&nbsp;"integeruser/CASIA-HWDB1.1-cnn"<CASIA-HWDB1.1-cnn@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[integeruser/CASIA-HWDB1.1-cnn] 你好！为什么我在训练的时候acc一直没有变化？损失也没有变化 (#1)




15个epoch之后，好像没有学到任何东西？

**Comment by Jockey721** [comment]
你好，我怀疑是数据集处理有问题？
我试着加了卷积层，也改变了学习率，训练的次数的话，15个epoch，损失都没有一点变化的趋势，一直原地踏步。最后，我直接使用了你训练好的模型，然后用4-draw_results.py得到结果，但也是0.005（1/200）？
ps：非常感谢你能回答我的问题，我也是刚刚接触，想练练手

**Comment by lyu-dimo** [comment]
此模型是我检出别人的项目，我当初在进行调整时也并未进行上传。所以，很抱歉不能够给予解答，相信其他人的模型可以给你更好的结果。

ps:当初参考的Google深度学习框架是GoogLeNet，映像中好像和DepthConcat层有关系，配图是在网络中获取的，希望能给予你帮助。
