### ISSUE TITLE
 你好！请问数字和字母有没有对应的文件编号？

### ISSUE THREAD

**Issue by menghonghan** [integeruser/CASIA-HWDB1.1-cnn#3]
你好，我只想要数据集中的非中文汉字部分，但是没有看到相应数据集存储信息，请问是分散在每个文件中吗，还是说有什么index说明，谢谢。

**Comment by integeruser** [comment]
Hello, my Chinese is a little rusty but if I understand the question to extract a different subset of characters you could simply modify appropriately [this part of the code](https://github.com/integeruser/CASIA-HWDB1.1-cnn/blob/master/src/2-dataset_to_subset.py#L19).
