### ISSUE TITLE
Question about new format GNTX in CASIA database

### ISSUE THREAD

**Issue by 4daJKong** [integeruser/CASIA-HWDB1.1-cnn#4]
I am confused about the format,'.gntx' in [CASIA-AHCDB](http://www.nlpr.ia.ac.cn/pal/CASIA-AHCDB.html). How to convert it to a png file, is it similar with 'gnt' format?

**Comment by integeruser** [comment]
Hello, the link you provided contains a table describing the format of GNTX files. It looks similar if not identical to the one used by the data set used in this project, so to extract bitmaps you could take inspiration from [our parsing code](https://github.com/integeruser/CASIA-HWDB1.1-cnn/blob/master/src/utils.py#L18).
